# Generated by Django 3.0.6 on 2020-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200514_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('released_time', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('find_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
